export const gridCells = [
  { label: 1, left: '160px', top: '640px', hasProject: true, projectId: 1, projectName: 'Grillwise' },
  { label: 2, left: '480px', top: '640px', hasProject: true, projectId: 2, projectName: 'Lorem ipsum' },
  { label: 3, left: '960px', top: '320px', hasProject: true, projectId: 3, projectName: 'Albed Price Book' },
  { label: 4, left: '640px', top: '320px', hasProject: true, projectId: 4, projectName: 'Abaco' },
  { label: 5, left: '320px', top: '320px', hasProject: true, projectId: 5, projectName: 'ApCollective' },
  { label: 6, left: '0px', top: '320px', hasProject: true, projectId: 6, projectName: 'Muso' },
  { label: 7, left: '-160px', top: '640px', hasProject: true, projectId: 7, projectName: 'Empathy Design' },
  { label: 8, left: '1120px', top: '640px', hasProject: true, projectId: 8, projectName: 'Syform' },
  { label: 9, left: '0px', top: '960px', hasProject: true, projectId: 9, projectName: 'Upcoming' },
  { label: 10, left: '320px', top: '960px', hasProject: true, projectId: 10, projectName: 'The Social Fablab' },
  { label: 11, left: '640px', top: '960px', hasProject: true, projectId: 11, projectName: 'Diversa' },
  { label: 12, left: '960px', top: '960px', hasProject: false, projectId: null },
  { label: 13, left: '1440px', top: '640px', hasProject: false, projectId: null },
  { label: 14, left: '1280px', top: '320px', hasProject: false, projectId: null },
  { label: 15, left: '1280px', top: '0px', hasProject: false, projectId: null },
  { label: 16, left: '960px', top: '0px', hasProject: false, projectId: null },
  { label: 17, left: '640px', top: '0px', hasProject: false, projectId: null },
  { label: 18, left: '320px', top: '0px', hasProject: false, projectId: null },
  { label: 19, left: '0px', top: '0px', hasProject: false, projectId: null },
  { label: 20, left: '-320px', top: '0px', hasProject: false, projectId: null },
  { label: 21, left: '-320px', top: '320px', hasProject: false, projectId: null },
  { label: 22, left: '-480px', top: '640px', hasProject: false, projectId: null },
  { label: 23, left: '800px', top: '640px', hasProject: false, projectId: null },
  { label: 24, left: '1280px', top: '960px', hasProject: false, projectId: null },
  { label: 25, left: '0px', top: '1280px', hasProject: false, projectId: null },
  { label: 26, left: '320px', top: '1280px', hasProject: false, projectId: null },
  { label: 27, left: '640px', top: '1280px', hasProject: false, projectId: null },
  { label: 28, left: '960px', top: '1280px', hasProject: false, projectId: null },
  { label: 29, left: '1280px', top: '1280px', hasProject: false, projectId: null },
  { label: 30, left: '1600px', top: '960px', hasProject: false, projectId: null },
  { label: 31, left: '-320px', top: '960px', hasProject: false, projectId: null },
  { label: 32, left: '1760px', top: '640px', hasProject: false, projectId: null },
  { label: 33, left: '1600px', top: '320px', hasProject: false, projectId: null },
  { label: 34, left: '1600px', top: '0px', hasProject: false, projectId: null },
];

export const projectIdsWithProjects = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11];